[tool.poetry]
name = "glip"
version = "0.1.0"
description = ""
authors = ["nobu-g <ueda-n127@hotmail.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.9.1%2Bcu111-cp39-cp39-linux_x86_64.whl" }
torchvision = "^0.10.1"
transformers = "~4.29.2"
einops = "^0.6.1"
shapely = "^2.0.1"
timm = "^0.9.2"
yacs = "^0.1.8"
tensorboardx = "^2.6"
ftfy = "^6.1.1"
prettytable = "^3.7.0"
pymongo = "^4.3.3"
setuptools = "^67.8.0"
pycocotools = "^2.0.6"
scipy = "^1.10.1"
opencv-python = "4.5.5.64"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
